name: Pylint

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
            REPORT_DIR="pylint-report-${{ github.event.pull_request.number }}"
            mkdir -p "$REPORT_DIR"
            pylint $(git ls-files '*.py') > "$REPORT_DIR/merge.log"

    - name: Upload Pylint report
      uses: actions/upload-artifact@v4
      with:
            name: pylint-report-${{ github.event.pull_request.number }}
            path: pylint-report-${{ github.event.pull_request.number }}/merge.log
